// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountList: typeof import('./components/special/profile/AccountList.vue')['default']
    ButtonWithIcon: typeof import('./components/general/ButtonWithIcon.vue')['default']
    ContentTItle: typeof import('./components/general/ContentTItle.vue')['default']
    GithubReposList: typeof import('./components/special/main/GithubReposList.vue')['default']
    ListContainer: typeof import('./components/general/ListContainer.vue')['default']
    MyFooter: typeof import('./components/general/MyFooter.vue')['default']
    ProfileItemTitle: typeof import('./components/special/profile/ProfileItemTitle.vue')['default']
    QiitaArticleList: typeof import('./components/special/main/QiitaArticleList.vue')['default']
    ReposArticleItem: typeof import('./components/special/main/ReposArticleItem.vue')['default']
    SystemCard: typeof import('./components/special/main/SystemCard.vue')['default']
    SystemList: typeof import('./components/special/main/SystemList.vue')['default']
    TechTag: typeof import('./components/general/TechTag.vue')['default']
    TechTagList: typeof import('./components/special/profile/TechTagList.vue')['default']
    TechTagWithCount: typeof import('./components/general/TechTagWithCount.vue')['default']
  }
}

export {}
