// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GithubReposList: typeof import('./components/molecules/GithubReposList.vue')['default']
    MainContainer: typeof import('./components/organisms/MainContainer.vue')['default']
    MyFooter: typeof import('./components/organisms/MyFooter.vue')['default']
    ProfileContainer: typeof import('./components/organisms/ProfileContainer.vue')['default']
    ProfileItemTitle: typeof import('./components/atoms/ProfileItemTitle.vue')['default']
    QiitaArticleList: typeof import('./components/molecules/QiitaArticleList.vue')['default']
    ReposArticleItem: typeof import('./components/molecules/ReposArticleItem.vue')['default']
    SystemCard: typeof import('./components/molecules/SystemCard.vue')['default']
    SystemList: typeof import('./components/molecules/SystemList.vue')['default']
    TechTag: typeof import('./components/atoms/TechTag.vue')['default']
    TechTagList: typeof import('./components/molecules/TechTagList.vue')['default']
  }
}

export {}
